### PR TITLE
Fixed zh_TW strings

### PR DESCRIPTION
**Pull request by olivertzeng**

### CODE REVIEW

**Comment by c22dev** [comment]
Asked @CySxL if he can review it, then I'll merge it !
Thanks a lot for your work.

**Comment by olivertzeng** [comment]
> Asked @CySxL if he can review it, then I'll merge it !
> 
> Thanks a lot for your work.

Tbh I think that this commit doesn't need to be reviewed by him  since I probably have more experience in translating than he does see my prs. I think I know what I'm doing and I've added a lot of new strings as well

**Comment by CySxL** [comment]
> Asked @CySxL if he can review it, then I'll merge it !
> 

It's not that good but I also lost the interest about this localizations, plus I'm really tired about this kid's shits...

**Comment by olivertzeng** [comment]
> 
> It's not that good but I also lost the interest about this localizations, plus I'm really tired about this kid's shits...

Oh ok lol

**Comment by CySxL** [comment]
Grow up kiddo. Rage quitting while people pointed out your problem seems not a sign of "I know what I'm doing". Just shut up and move your a$$ cuz i don't literally care about what you had done or about to do until u act civilized.

**Comment by olivertzeng** [comment]
@c22dev Will you merge the pr since cysxl says that he doesn't care

**Comment by c22dev** [comment]
I still need someone to review this and I def won't merge it without it.
And considering your aggressiveness here, this adds up to the reasons why I need a reviewer.

**Comment by olivertzeng** [comment]
> I still need someone to review this and I def won't merge it without it.
> And considering your aggressiveness here, this adds up to the reasons why I need a reviewer. 

Fair enough

**Comment by olivertzeng** [comment]
> I still need someone to review this and I def won't merge it without it.
> And considering your aggressiveness here, this adds up to the reasons why I need a reviewer. 

There are probably some minor mistakes in my translations and a reviewer could just fix my problems

**Comment by c22dev** [comment]
Nope I haven't yet.
Sorry !

**Comment by olivertzeng** [comment]
Oh

**Comment by c22dev** [comment]
Can you update your commits so I can merge it ?

**Comment by olivertzeng** [comment]
> Can you update your commits so I can merge it ?

No problem

**Comment by olivertzeng** [comment]
> Can you update your commits so I can merge it ?

This will take some time as it requires my computer to do this work
image

**Pull request closed without merging**
